"""
core/actions.py – Automated response actions.

Actions
-------
- generate_htaccess()   : Apache .htaccess Deny rules
- generate_nginx_acl()  : Nginx deny block
- generate_iptables()   : iptables shell script (Linux firewall)
- send_alert_email()    : SMTP email alert (if configured)

All generators return plain text; nothing is written to the filesystem
automatically.  The user downloads / copies the output explicitly.
"""

import logging
import os
import smtplib
import ssl
from email.message import EmailMessage
from typing import List, Optional

logger = logging.getLogger(__name__)

_BANNER = (
    "# Generated by IPWatchdog – https://github.com/your-org/IPWatchdog\n"
    "# Review before applying. These rules block all traffic from listed IPs.\n\n"
)


class ActionEngine:
    """Generates firewall / server block rules and optional email alerts."""

    # ------------------------------------------------------------------
    # Rule generators
    # ------------------------------------------------------------------

    def generate_htaccess(self, ips: List[str]) -> str:
        """Apache .htaccess block rules."""
        if not ips:
            return "# No IPs to block."
        lines = [_BANNER, "Order Allow,Deny\nAllow from all\n"]
        for ip in _dedupe(ips):
            lines.append(f"Deny from {ip}")
        return "\n".join(lines)

    def generate_nginx_acl(self, ips: List[str]) -> str:
        """Nginx geo/deny block for inclusion in nginx.conf."""
        if not ips:
            return "# No IPs to block."
        lines = [_BANNER, "geo $blocked_ip {\n    default 0;"]
        for ip in _dedupe(ips):
            lines.append(f"    {ip} 1;")
        lines.append("}\n")
        lines.append(
            "# In your server block add:\n"
            "# if ($blocked_ip) { return 403; }"
        )
        return "\n".join(lines)

    def generate_iptables(self, ips: List[str]) -> str:
        """Linux iptables DROP rules (shell script)."""
        if not ips:
            return "# No IPs to block."
        lines = [_BANNER, "#!/bin/bash", "# Run as root: sudo bash block_ips.sh\n"]
        for ip in _dedupe(ips):
            lines.append(f"iptables -I INPUT -s {ip} -j DROP")
        lines.append("\necho 'Rules applied.'")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Email alerting
    # ------------------------------------------------------------------

    def send_alert_email(
        self,
        flagged_ips: List[str],
        summary: dict,
        recipient: Optional[str] = None,
    ) -> bool:
        """
        Send an alert email via SMTP.
        Credentials are loaded from environment variables (never hardcoded).
        Returns True on success, False on failure.
        """
        smtp_host = os.environ.get("SMTP_HOST", "")
        smtp_port = int(os.environ.get("SMTP_PORT", "587"))
        smtp_user = os.environ.get("SMTP_USER", "")
        smtp_pass = os.environ.get("SMTP_PASSWORD", "")
        to_addr   = recipient or os.environ.get("ALERT_RECIPIENT", "")

        if not all([smtp_host, smtp_user, smtp_pass, to_addr]):
            logger.debug("Email alerting not configured (non-fatal).")
            return False

        try:
            msg = EmailMessage()
            msg["Subject"] = f"[IPWatchdog] {len(flagged_ips)} suspicious IP(s) detected"
            msg["From"] = smtp_user
            msg["To"] = to_addr
            msg.set_content(
                f"IPWatchdog Alert\n"
                f"{'─' * 40}\n"
                f"Total requests : {summary.get('total_requests', '?')}\n"
                f"Unique IPs     : {summary.get('unique_ips', '?')}\n"
                f"Suspicious IPs : {len(flagged_ips)}\n\n"
                f"Top flagged IPs:\n"
                + "\n".join(f"  • {ip}" for ip in flagged_ips[:20])
            )
            context = ssl.create_default_context()
            with smtplib.SMTP(smtp_host, smtp_port) as server:
                server.ehlo()
                server.starttls(context=context)
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)
            logger.info("Alert email sent to %s", to_addr)
            return True
        except Exception as exc:
            logger.warning("Failed to send alert email (non-fatal): %s", exc)
            return False


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _dedupe(ips: List[str]) -> List[str]:
    """Return deduplicated IPs, preserving order."""
    seen = set()
    out = []
    for ip in ips:
        if ip not in seen:
            seen.add(ip)
            out.append(ip)
    return out
